name: kaloricke_tabulky_02
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  two_dimensional_scrollables: ^0.3.0
  provider: ^6.0.5
  dropdown_button2: ^2.3.8
 
 
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0+3
  sqlite3_flutter_libs: ^0.5.18
  marquee: ^2.2.3
  intl: ^0.19.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1
  google_sign_in: ^6.2.1
  expandable_widgets: ^1.0.3+1
  expand_widget: ^3.1.1
  connectivity: ^3.0.6
  toggle_list: ^0.3.1
  conditional_builder_null_safety: ^0.0.6
  supabase_flutter: ^2.5.4
  supabase_extensions: ^1.0.1
  top_snackbar_flutter: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  draggable_bottom_sheet: ^1.0.2
  openfoodfacts: ^3.11.0
  flutter_barcode_scanner: ^2.0.0
  loading_animation_widget: ^1.2.1
  fl_chart: ^0.68.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "asset/appIcon.png" 
  
  android: true
  ios: true


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/db/mainFoodDatabase.db
    - assets/db/example.db
    - assets/foodDatabase.db
    - assets/gym.png
    - assets/google_icon.png
    - assets/icons/icon_biceps.png
    - assets/icons/icon_bodybuilder.png
    - assets/icons/icon_half_bodybuilder.png
