name: kaloricke_tabulky_02
description: A new Flutter project.

version: 1.0.2+4

environment:
  sdk: '>=3.1.2 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dropdown_button2: ^2.3.8
 
 
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0+3
  sqlite3_flutter_libs: ^0.5.18
# marquee: ^2.2.3
  intl: ^0.19.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1
  google_sign_in: ^6.2.1
  expandable_widgets: ^1.0.3+1
  expand_widget: ^3.1.1
  toggle_list: ^0.3.1
  conditional_builder_null_safety: ^0.0.6
  supabase_flutter: ^2.5.4
  supabase_extensions: ^1.0.1
  top_snackbar_flutter: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  draggable_bottom_sheet: ^1.0.2
  openfoodfacts: ^3.11.0
  # flutter_barcode_scanner: ^2.0.0
  loading_animation_widget: ^1.2.1
  fl_chart: ^0.69.0
  stroke_text: ^0.0.3
  flutter_vector_icons: ^2.0.0
  device_info_plus: ^10.1.2
  flutter_localizations:
    sdk: flutter
  diacritic: ^0.1.5
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  date_picker_plus: ^4.1.0
  text_scroll: ^0.2.0
  timelines: ^0.1.0
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  country_icons: ^3.0.0
  email_validator: ^3.0.0
  tutorial_coach_mark: ^1.2.11
  # flutter_marquee: ^2.0.1
  # marquee: ^2.2.3
  # fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/gym_google1.png"
  
  android: true
  ios: true


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/db/mainFoodDatabase.db
    - assets/db/example.db
    - assets/foodDatabase.db
    - assets/gym.png
    - assets/gym_google1.png
    - assets/gym_google2.png
    - assets/google_icon.png
    - assets/icons/icon_biceps.png
    - assets/icons/icon_bodybuilder.png
    - assets/icons/icon_half_bodybuilder.png
    - assets/Tutorial pictures/tutorial_check_exercises.png
    - assets/Tutorial pictures/tutorial_new_exercise.png
    - assets/Tutorial pictures/tutorial_split.png
    - assets/Tutorial pictures/tutorial_tap_exercise.png
    - assets/Tutorial pictures/tutorial_new_value_exercise.png
    - assets/Tutorial pictures/tutorial_add_new_value_exercise.png
    - assets/Tutorial pictures/tutorial_swipe_up_exercise.png
    - assets/Tutorial pictures/tutorial_historical_exercise.png
    - assets/Tutorial pictures/tutorial_add_button_food.png
    - assets/Tutorial pictures/tutorial_search_bar.png
    - assets/Tutorial pictures/tutorial_search_items.png
    - assets/Tutorial pictures/tutorial_new_split_select.png
    - assets/Tutorial pictures/tutorial_new_split_name_split.png



    - assets/langs/cs.json
    - assets/langs/en.json
    - assets/langs/de.json
