name: kaloricke_tabulky_02
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  two_dimensional_scrollables: ^0.0.1
  provider: ^6.0.5
  dropdown_button2: ^2.3.8
 

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0+3
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "asset/appIcon.png" 
  android: true
  ios: true


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/db/mainFoodDatabase.db

